# (C) Copyright 2026, by Ross Richardson
#
# Webserver.
#
# @author ross richardson
#

model.prefix=SimPaths
model.package=simpaths.model
experiment.package=simpaths.experiment
cors.allowed.hosts=http://localhost:5001,https://jas-mine.web.app,https://simpaths.org
allowDetailedDataAccess=true
